language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r Conectores/SNMP/requirements.txt
  - pip install -r Conectores/MQTT/requirements.txt
script:
  - python3 Conectores/SNMP/unittest.py
    #  - python3 Conectores/MQTT/unittest.py
