language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r Conectores/SNMP/requirements.txt Conectores/MQTT/requirements.txt
virtualenv:
  system_site_packages: true
script:
  - Conectores/SNMP/unittest.py
  - Conectores/MQTT/unittest.py
