dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
addons:
  sonarcloud:
    organization: "greencorecr"
    token:
      secure: ${SONAR_TOKEN}
install:
  - pip install -r software/SNMP/requirements.txt
  - pip install -r software/ttn2db/requirements.txt
  - pip install -r software/snmp2db/requirements.txt
  - npm install -g markdown-link-check
script:
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN}
  - find . -name \*.md -exec markdown-link-check {} +
  - ( cd software/ttn2db/test/ ; python3 -m unittest discover -v )
  - ( cd software/snmp2db/test/ ; python3 -m unittest discover -v )
