#!/usr/bin/python

def inventory_sensor03_gotas(info):
   inventory = []
   for line in info:
   	tipo = line[0]
        valor = line[1]
	inventory.append((tipo, valor))
   #print inventory
   return inventory

def check_sensor03_gotas(item, _no_params, info):
   for line in info:
        tipo = line[0]
        valor = line[1]
	# OK cuando estado es 0 (ausencia de gotas)
        if tipo == "gotas" and valor == "0":
	   infotext = "No se detectan gotas, estado:" + valor
	   return 0, infotext, [ ("estado", valor) ]
	# WARNING cuando estado es 1 (gotas detectadas)
	elif tipo == "gotas" and valor == "1":
	   infotext = "Atencion gotas detectadas, favor revisar, estado: " + valor
	   return 1, infotext, [ ("estado", valor) ]
	# CRITICAL cuando estado es 2 (no se recibe informacion)
	else:
	   infotext = "No se esta recibiendo informacion, estado: " + valor
	   return 2, infotext, [ ("estado", valor) ]

check_info["sensor03_gotas"] = {
    "check_function"        : check_sensor03_gotas,
    "inventory_function"    : inventory_sensor03_gotas,
    "service_description"   : "Sensor",
    "snmp_info"             : ( ".1.3.6.1.4.1.8072.1.3.2.4.1.2.14.115.101.110.115.111.114.48.51.45.103.111.116.97.115", [ "1", "2" ] ) ,
    "has_perfdata"	    : True,
}
