#!/usr/bin/python

def inventory_sensor01_temperatura(info):
   inventory = []
   for line in info:
   	tipo = line[0]
        valor = line[1]
	inventory.append((tipo, valor))
   #print inventory
   return inventory

def check_sensor01_temperatura(item, _no_params, info):
   for line in info:
        tipo = line[0]
        valor = line[1]
	# OK cuando sea menor a 30 grados centigrados
        if tipo == "temperatura" and valor != "0" and valor != "12336" and valor < "30":
	   infotext = "temperatura actual: " + valor
	   return 0, infotext, [ ("temperatura", valor) ]

	# WARNING cuando la temperatura este entre 30 y 40 grados centigrados
	elif tipo == "temperatura" and valor > "30" and valor < "40":
           infotext = "temperatura actual: " + valor
           return 1, infotext, [ ("temperatura", valor) ]
	
	# CRITICAL cuando la temperatura sea mayor de 40 o se reciban datos
	else:
           infotext = "temperatura actual: " + valor
           return 2, infotext, [ ("temperatura", valor) ]

check_info["sensor01_temperatura"] = {
    "check_function"        : check_sensor01_temperatura,
    "inventory_function"    : inventory_sensor01_temperatura,
    "service_description"   : "Sensor",
    "snmp_info"             : ( ".1.3.6.1.4.1.8072.1.3.2.4.1.2.20.115.101.110.115.111.114.48.49.45.116.101.109.112.101.114.97.116.117.114.97", [ "1", "2" ] ) ,
    "has_perfdata"	    : True,
}
